# Generated by Django 5.1.7 on 2025-03-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0002_result_elo_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedSailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sailor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sailors.sailor')),
            ],
        ),
    ]
