# Generated by Django 5.1.7 on 2025-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0003_interestedsailor'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedsailor',
            name='last_heard_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestedsailor',
            name='last_reached_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
