# Generated by Django 5.1.7 on 2025-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailors', '0005_interestedsailor_coach_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedsailor',
            name='sailing_resume',
            field=models.FileField(blank=True, null=True, upload_to='sailing_resumes/'),
        ),
        migrations.AddField(
            model_name='interestedsailor',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
    ]
