# Generated by Django 5.1.7 on 2025-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='last_heard_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_reached_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
